### ISSUE TITLE
Terraform AWS provider is hardcoded

### ISSUE THREAD

**Issue by tomi-bigpi** [Flaconi/terraform-aws-iam-ses-user#8]
Hi,

The hardcoded provider (especially the region) make it hard to use this module as-is. It would probably be better to leave out the whole `provider` block and let the consumer of the module define that separately.

https://github.com/Flaconi/terraform-aws-iam-ses-user/blob/93014af5170a89600a6c69838f367a715f13c719/main.tf#L3

Thanks

**Comment by danvaida** [comment]
Indeed... Except for very special cases, the TF modules should not contain any provider definitions. A linked PR is now addressing this.
